#!/usr/bin/env bash

last=`fd -td . | grep -v templates | tail -n1`
next=$((last + 1))
next_formatted=`printf "%02d" $next`

cp -R templates $next_formatted
source cd $_

link="https://adventofcode.com/2021/day/$next"
if [[ "$OSTYPE" == "darwin"* ]]; then
  open -a "google chrome" $link
else
  echo $link
fi

